[llm]
url='http://100.99.54.84:11434/v1'
key='ollama'
model='general_small'

[gotify]
url='https://gotify.example.com'
key='1234567890'

[pdoc_ai]
llm_baseurl="http://100.99.54.84:11434/v1"
llm_key="ollama"
llm_model="code_assist_large"